---
title: "Lecture 3: Intro to ggplot2, Coding Style"
date: 2025-07-01
summary: "Visualizing Data with ggplot2, Coding Style in R"
url_slides: 03-slides.qmd
url_code: csp-materials/ggplot2-style
page-layout: full
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Info and Materials

* **Date**: {{< meta date >}}
* **Topics**: {{< meta summary >}}
* **Slides**: [View Slides]({{< meta url_slides >}})
* **Code**: `usethis::use_course("{{< meta url_code >}}")`


## Learning Objectives

- Recognize the role of visualization in exploring and communicating data
- Understand the basic principles of the "Layered Grammar of Graphics"
- Create simple layered plots using `ggplot2`
- Apply correct coding style practices when writing R code


## Before Class

- Review the Lecture 2 materials to get ready for today's in-class quiz
- Start [Homework 1](../hw/hw01.qmd). Have questions or need help? Join us for Office Hours right after class!
- Bring your laptop to every class


## Readings

Skim the readings before or after class to get the big picture and prep for quizzes and assignments:

* [Chapter 4 "Workflow: Code Style"](https://r4ds.hadley.nz/workflow-style) from "R for Data Science" 2nd Edition 
* [Chapter 1 "Data Visualization"](https://r4ds.hadley.nz/data-visualize) from "R for Data Science" 2nd Edition

<!-- To be able to follow today's lecture, you need to read these chapter, especially Chapter 1! -->

Additional Resources (not needed for quizzes or homework, but helpful to dive deeper):

* [ggplot2 Cheat Sheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/data-visualization.pdf)
* [ggplot2 Official Documentation](https://ggplot2.tidyverse.org/index.html)
* [ggplot2: Elegant Graphics for Data Analysis, 2nd Edition](https://ggplot2-book.org/) by Hadley Wickham. Excellent resource for learning the intricacies of `ggplot2`
* [R Graphics Cookbook, 2nd edition](https://r-graphics.org/) by Winston Chang. A practical guide with 150 examples to generate quality graphics based on the data you wish to present
* ["The `tidyverse` style guide"](https://style.tidyverse.org/index.html)
<!-- check css website for more -->

