---
title: "Lecture 8: Data Structures, Base R"
date: 2025-07-22
summary: "Intro to Data Structures and Base R"
url_slides: 08-slides.qmd
url_code: csp-materials/base-r
page-layout: full
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Info and Materials

* **Date**: {{< meta date >}}
* **Topics**: {{< meta summary >}}
* **Slides**: [View Slides]({{< meta url_slides >}})
* **Code**: No in-class code to download


## Learning Objectives

- Understand what Base R is, and how it differs from the Tidyverse
- Identify R data types and structures  
- Explore R vectors 
- Subset data using Base R syntax (optional)


## Before Class

- Review Lecture 7 materials to get ready for today's in-class quiz
- Bring your laptop to every class


## Readings

Skim the readings before or after class to get the big picture and prep for quizzes and assignments:

* [Chapter 20 “Vectors”](https://r4ds.had.co.nz/vectors.html) in "R for Data Science" 1st Edition. I assigned the 1st Edition because I find it a bit clearer on this topic than the 2nd Edition, but you might want to take a look also at [Chapter 12 "Logical Vectors"](https://r4ds.hadley.nz/logicals) and [Chapter 13 "Numbers"](https://r4ds.hadley.nz/numbers) of the 2nd Edition and decide what you prefer. Either works!
* [Chapter 27 "A field guide to base R"](https://r4ds.hadley.nz/base-r) in "R for Data Science" 2nd Edition.

